MODEL:
  META_ARCHITECTURE: "CenterNet"
  BACKBONE:
    NAME: "build_poseresnet_backbone"
  POSERESNETS:
    DEPTH: 18
    OUT_FEATURES: ["deconv"]
    SIZE_DIVISIBILITY: 4
  CENTERNET:
    IN_FEATURES: ["deconv"]
    HM_WEIGHT: 1
    WH_WEIGHT: 0.1
    WH_LOSS: "l1"
    DOWN_RATIO: 4
    HEAD_CONV_DIMS: [64]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.003
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
  AMP: 
    ENABLED: True
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
